apiVersion: v2
name: windmill-hub
description: Helm chart for deploying the Windmill Hub
type: application
maintainers:
  - name: Windmill Labs
    email: support@windmill.dev
    url: https://windmill.dev
version: 0.1.24
appVersion: "1.0.4"
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.3.1
